name: IAR CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - 'README.md'
    - '.devcontainer/**'
    - '.vscode/**'

env:
  # Set IAR_LMS_BEARER_TOKEN on: 
  # - GitHub Actions: https://github.com/<user|org>/riscv-board-examples/settings/secrets/actions
  # - GitHub Codespaces: https://github.com/<user|org>//riscv-board-examples/settings/secrets/codespaces
  # - Local Machine: export IAR_LMS_BEARER_TOKEN=<your-secret-CI-token>
  IAR_LMS_BEARER_TOKEN: ${{ secrets.IAR_LMS_BEARER_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/iarsystems/riscv
    steps:
    - name: Invoke the IAR C/C++ Compiler for RISC-V
      run: iccriscv --version
    - name: Checkout project
      uses: actions/checkout@v4
    - name: CMake - Configure CXRISCV preset
      run: cmake --preset cxriscv
    - name: CMake - Build Debug preset
      run: cmake --build --preset debug --verbose
    - name: CMake - Build Release preset
      run: cmake --build --preset release --verbose
    - name: CMake - Build Release With Debug Info preset
      run: cmake --build --preset relwithdebinfo --verbose
    - name: CMake - Build Minimum Size Release preset
      run: cmake --build --preset minsizerel --verbose
    - name: CMake - Build High Speed preset
      run: cmake --build --preset highspeed --verbose
    - name: CMake - Build Maximum Speed preset
      run: cmake --build --preset maxspeed --verbose

